### ISSUE TITLE
Check Audio script fails.

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#110]
Following the latest round of merges involving audio please note that the Check Audio script fails. This is the traceback
```
Playing a test sound...
Traceback (most recent call last):
  File "/home/pi/voice-recognizer-raspi/checkpoints/check_audio.py", line 198, in <module>
    main()
  File "/home/pi/voice-recognizer-raspi/checkpoints/check_audio.py", line 191, in main
    do_checks()
  File "/home/pi/voice-recognizer-raspi/checkpoints/check_audio.py", line 172, in do_checks
    if not check_speaker_works():
  File "/home/pi/voice-recognizer-raspi/checkpoints/check_audio.py", line 130, in check_speaker_works
    play_wav(TEST_SOUND_PATH)
  File "/home/pi/voice-recognizer-raspi/checkpoints/check_audio.py", line 77, in play_wav
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '/home/pi/voice-recognizer-raspi/src/aiy/audio.py', 'play', '/usr/share/sounds/alsa/Front_Center.wav']' returned non-zero exit status 1
Press Enter to close...
```

I tried the script immediately before updating my install and it worked perfectly.

**Comment by drigz** [comment]
Looks like this was broken by #97, which removed `main()` from audio.py. We could fix by adding `main()` back to audio.py, or by making `check_audio.py` add `../src` to `sys.path` and `import aiy.audio`.

I'd suggest the latter, as it is more like what users of the module will be doing. @enetor, WDYT?
