### ISSUE TITLE
Follow-on queries not supported.

### ISSUE THREAD

**Issue by ali1234** [google/aiyprojects-raspbian#12]
To reproduce, ask "What can you do?" Assistant will ask if you want more suggestions. Say "Yes", and assistant will respond that it does not understand. Also affects the trivia quiz mode.

Attempting the same with googlesamples-assistant also fails. It does understand follow-on queries but crashes as soon as it starts playing the response to one:

```
(google-assistant-sdk) al@al-desktop:~/aiyprojects-raspbian/src$ googlesamples-assistant
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:End of audio request detected
INFO:root:Transcript of user request: "what can you do".
INFO:root:Playing assistant response.
INFO:root:Expecting follow-on query from user.
INFO:root:Finished playing assistant response.
INFO:root:Recording audio request.
INFO:root:End of audio request detected
INFO:root:Transcript of user request: "yes".
INFO:root:Playing assistant response.
INFO:root:Expecting follow-on query from user.
Traceback (most recent call last):
  File "/home/al/google-assistant-sdk/bin/googlesamples-assistant", line 11, in <module>
    sys.exit(main())
  File "/home/al/google-assistant-sdk/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/al/google-assistant-sdk/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/al/google-assistant-sdk/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/al/google-assistant-sdk/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/al/google-assistant-sdk/lib/python3.5/site-packages/googlesamples/assistant/__main__.py", line 234, in main
    grpc_deadline):
  File "/home/al/google-assistant-sdk/lib/python3.5/site-packages/grpc/_channel.py", line 363, in __next__
    return self._next()
  File "/home/al/google-assistant-sdk/lib/python3.5/site-packages/grpc/_channel.py", line 346, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Failed parsing HTTP/2)>
```

**Comment by drigz** [comment]
Thanks for the report! I'll look in to how we could add follow-on queries.

Regarding the error from googlesamples-assistant, what version are you using? That crash may have been fixed by [7da41cf](https://github.com/googlesamples/assistant-sdk-python/commit/7da41cfbcd4f5aa0e0e34aa01a1ea1fdfb04b83b), but if you're using 0.1.0 you won't have that.

**Comment by ali1234** [comment]
I installed everything by following scripts/install-deps.sh so I guess I have 0.1.0.

**Comment by akrs** [comment]
It looks like you'll need to examine `ConverseResponse.result.microphone_mode` to see if it's `CLOSE_MICROPHONE` or `DIALOG_FOLLOW_ON`. If it's a follow on, there should be a new `ConverseRequest` with the `ConverseState` from the last `ConverseResponse` embeded in the `ConverseConfig`.
