### ISSUE TITLE
How to Connect Google service from China ? ERROR !

### ISSUE THREAD

**Issue by makelove** [google/aiyprojects-raspbian#169]
I am a programer from Beijing China,just buy AIY kit a few days ago
Everythings is OK,but Network is big problem,
I had install Lantern https://getlantern.org/ to skip over GFW
but jump out another problems !

-
How I setup :
add this at the end of ~/.bashrc file
```bash
#proxy
export http_proxy='http://192.168.0.159:50493'
export https_proxy='https://192.168.0.159:50493'
export no_proxy=localhost,127.0.0.0/8
```
192.168.0.159 is my computer

-
RESULT:
check_audio.desktop OK
check_wifi.desktop OK
check_cloud.desktop tell me :
Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Project piaiy-185305 (#903298171188) has billing disabled. Please enable it 
**--I know what happen**

-
~/AIY-voice-kit-python/src
assistant_grpc_demo.py is ONLY working ,fine
sometime it also ERROR
```bash
(env) pi@AIY:~/AIY-voice-kit-python/src $ ./assistant_grpc_demo.py
/home/pi/AIY-voice-kit-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
Press the button and speak
[2017-11-08 15:53:23,220] INFO:recorder:started recording
Listening...
Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 810, in _prepare_proxy
    conn.connect()
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/auth/transport/requests.py", line 112, in __call__
    **kwargs)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/requests/adapters.py", line 512, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/src/aiy/_apis/_speech.py", line 257, in do_request
    service = self._make_service(self._channel_factory.make_channel())
  File "/home/pi/AIY-voice-kit-python/src/aiy/_apis/_speech.py", line 70, in make_channel
    self._credentials.refresh(request)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/oauth2/credentials.py", line 126, in refresh
    self._client_secret))
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/oauth2/_client.py", line 189, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/oauth2/_client.py", line 104, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/auth/transport/requests.py", line 115, in __call__
    raise exceptions.TransportError(exc)
google.auth.exceptions.TransportError: EOF occurred in violation of protocol (_ssl.c:600)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./assistant_grpc_demo.py", line 54, in <module>
    main()
  File "./assistant_grpc_demo.py", line 42, in main
    text, audio = assistant.recognize()
  File "/home/pi/AIY-voice-kit-python/src/aiy/assistant/grpc.py", line 49, in recognize
    response = self._request.do_request()
  File "/home/pi/AIY-voice-kit-python/src/aiy/_apis/_speech.py", line 270, in do_request
    raise Error('Exception in speech request') from exc
aiy._apis._speech.Error: Exception in speech request
```

assistant_library_demo.py ERROR :ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```bash
(env) pi@AIY:~/AIY-voice-kit-python/src $ ./assistant_library_demo.py
/home/pi/AIY-voice-kit-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
Say "OK, Google" then speak, or press Ctrl+C to quit...
E1108 15:56:06.265621038    1314 handshake.c:128]            Security handshake failed: {"created":"@1510127766.265482237","description":"Handshake read failed","file":"../../third_party/grpc/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1510127766.265463903","description":"FD shutdown","file":"../../third_party/grpc/src/core/lib/iomgr/ev_epoll_linux.c","file_line":1045}]}
E1108 15:56:06.278022309    1314 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```

assistant_library_with_button_demo.py Same ERROR as assistant_library_demo.py

cloudspeech_demo.py ERROR :File "/home/pi/AIY-voice-kit-python/src/aiy/_drivers/_button.py", line 57, in __del__
AttributeError: 'NoneType' object has no attribute 'cleanup'
```bash
(env) pi@AIY:~/AIY-voice-kit-python/src $ ./cloudspeech_demo.py
/home/pi/AIY-voice-kit-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
Press the button and speak
Listening...
Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/src/aiy/_apis/_speech.py", line 257, in do_request
    service = self._make_service(self._channel_factory.make_channel())
  File "/home/pi/AIY-voice-kit-python/src/aiy/_apis/_speech.py", line 70, in make_channel
    self._credentials.refresh(request)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/oauth2/service_account.py", line 310, in refresh
    request, self._token_uri, assertion)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/oauth2/_client.py", line 143, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/oauth2/_client.py", line 109, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/pi/AIY-voice-kit-python/env/lib/python3.4/site-packages/google/oauth2/_client.py", line 59, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.', '{\n  "error" : "invalid_grant",\n  "error_description" : "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems."\n}')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./cloudspeech_demo.py", line 53, in <module>
    main()
  File "./cloudspeech_demo.py", line 37, in main
    text = recognizer.recognize()
  File "/home/pi/AIY-voice-kit-python/src/aiy/cloudspeech.py", line 47, in recognize
    return self._request.do_request().transcript
  File "/home/pi/AIY-voice-kit-python/src/aiy/_apis/_speech.py", line 270, in do_request
    raise Error('Exception in speech request') from exc
aiy._apis._speech.Error: Exception in speech request
Exception ignored in: <bound method Button.__del__ of <aiy._drivers._button.Button object at 0x747cead0>>
Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/src/aiy/_drivers/_button.py", line 57, in __del__
AttributeError: 'NoneType' object has no attribute 'cleanup'
```

-
First time ,it's working fine with assistant_grpc_demo.py,now it's ERROR
you can check my final video :https://www.youtube.com/watch?v=Y9nQisOEvf8
Please help me How to setup Network proxy problems, otherwise it will be trash of useless .
Thank you !

-
then I try to use **Ubuntu Mate** with AIY kits,but fail too.
https://github.com/google/aiyprojects-raspbian/issues/168

**Comment by makelove** [comment]
I had finish moving aiyprojects  to Ubuntu Mate,
I had try all demos,still have same problems ! ONLY assistant_grpc_demo.py is working
even I setup Network Proxy in system-control
<img width="386" alt="wx20171110-222045 2x" src="https://user-images.githubusercontent.com/6279340/32662576-00d7da46-c666-11e7-94b1-fb1322fe25ea.png">

-
Why I move to Ubuntu Mate,because I think **setup Network Proxy in system-control** can avoid these problems or bugs

**Comment by drigz** [comment]
>google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.', '{\n  "error" : "invalid_grant",\n  "error_description" : "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems."\n}')

This error normally occurs when the time is incorrect on the RPi, which you can fix with `sudo /usr/sbin/ntpdate -u pool.ntp.org`.

Regarding the other issues, the product is not launched and supported in China.
