### ISSUE TITLE
use pyaudio for recording

### ISSUE THREAD

**Issue by ghost** [google/aiyprojects-raspbian#245]
I tried to put voice kit on my pyaudio lib code. but it seens not working.

i set param as below

CHUNK_SIZE = 1024 
FORMAT = pyaudio.paInt16
RATE = 16000

and when i 

```   
   p = pyaudio.PyAudio()

   ....................................(other code)

    sample_width = p.get_sample_size(FORMAT)
    stream.stop_stream()
    stream.close()

    r = normalize(r)
    r = trim(r)
    r = add_silence(r, 0.5)
    return sample_width, r
```

the code crash and shows 

```
Traceback (most recent call last):
  File "voicekit.py", line 224, in <module>
    record_to_file(fileName)
  File "voicekit.py", line 156, in record_to_file
    sample_width, data = record()
  File "voicekit.py", line 115, in record
    frames_per_buffer=CHUNK_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid input device (no default output device)
```

how can i pass this error, thanks

**Comment by drigz** [comment]
We don't support PyAudio (we found that we got lots of unpredictable problems, so we switched to using `arecord` and `aplay` in `aiy.audio`).

If you want to keep using PyAudio, you could ask for support on the [AIY Forums](https://www.raspberrypi.org/forums/viewforum.php?f=114), or in a PyAudio community.
