### ISSUE TITLE
AIY Vision kit 1.1 Pi WH - Cannot use Picamera() inside a function or a loop

### ISSUE THREAD

**Issue by davesdere** [google/aiyprojects-raspbian#390]
Hi there!
I have been fiddling around the Picamera module a little bit and I noticed that when using Picamera() inside a function or a loop I would consistently get this error message.
```
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x13a49b0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
Traceback (most recent call last):
  File "funSetup_v3.py", line 388, in <module>
    main()
  File "funSetup_v3.py", line 385, in main
    camera = PiCamera()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/usr/lib/python3/dist-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources
```
I checked the cables. All good. I have the most recent update, upgrade and firmware update available.
```
sudo apt-get update
sudo apt-get upgrade
sudo rpi-update
```
I even run this for good measure.
`sudo apt --fix-broken install`

I tried increasing the memory, by different increment up to 256. It didn't work.
I also rebooted every time I had this error message.
Between each attempt I also did
`pkill python3`

Then...
I tried the 'with' way.
```
def timelapse():
    with picamera.PiCamera() as camera:
```
I also tried to define the camera outside my function.
```
camera = Picamera()
def recordVideo():
    camera.resolution = (1640, 922)  # Full Frame, 16:9 (Camera v2)
```
Then Python told me the variable was accessed before it was created.

I also tried to give the camera global scope.
```
global camera
camera = Picamera()
def recordVideo():
    camera.resolution = (1640, 922)  # Full Frame, 16:9 (Camera v2)
```
Any workaround I missed about this?

**Comment by dmitriykovalev** [comment]
It's definitely not related to inside/outside function or loop. Can you check camera using `raspivid` or `raspistill` command line tools? Did you disable JoyDemo service running in background (it uses the camera and camera cannot be shared between processes)?

**Comment by davesdere** [comment]
Hi @dmitriykovalev !
I disabled the JoyDemo (First thing I do on a fresh install, those beeps drive me nuts lol). I will take your word on the scope part because since then I have been going about it differently. I did check the `raspivid` and `raspistill` command line tools and got the same error. 
Coming back to the fact that the camera cannot be shared between processes... I know there's the splitter in the doc for streaming and recording at the same time, but what about when the script crashes (e.g. because of a lack of memory) or in the event of a KeyboardInterrupt (without a try/catch). How would you free the camera? The `pkill python3` doesn't seem to work 100% of the time. Is there a way to free the camera? Also, Is there a way to unload the inference models? Can `inference.close()` be used?

**Comment by dmitriykovalev** [comment]
Regarding close() functions: camera.close() frees all camera resources and stops camera, inference.close() frees inference resources (unloads model from the bonnet) and stops inferences. That's why you should typically use "with picamera.PiCamera() as camera" or "with CameraInference() as inference" to have these close() functions called automatically.

Can you try our example code (e.g. face_detection_camera.py), does it work on your setup?

**Comment by davesdere** [comment]
Hi Dmitry! Thanks for your comment.

I tried the face_detection_camera.py. Here's the result.
```
pi@raspberrypi:~/AIY-projects-python/src/examples/vision $ ./face_detection_camera.py
Iteration #0: num_faces=0  
Iteration #1: num_faces=0  
Iteration #2: num_faces=0  
Iteration #3: num_faces=0
Iteration #4: num_faces=0
Iteration #5: num_faces=0
Iteration #6: num_faces=0
Iteration #7: num_faces=0
Iteration #8: num_faces=0
Iteration #9: num_faces=0
Iteration #10: num_faces=0
Iteration #11: num_faces=0
Iteration #12: num_faces=0
Iteration #13: num_faces=0
Iteration #14: num_faces=0
Iteration #15: num_faces=0
Iteration #16: num_faces=0
Iteration #17: num_faces=0
Iteration #18: num_faces=0
Iteration #19: num_faces=0
Iteration #20: num_faces=0
Iteration #21: num_faces=0
Iteration #22: num_faces=0
Iteration #23: num_faces=0
Iteration #24: num_faces=0
Iteration #25: num_faces=0
Iteration #26: num_faces=0
Iteration #27: num_faces=0
Iteration #28: num_faces=0
Iteration #29: num_faces=0
Iteration #30: num_faces=0
Iteration #31: num_faces=0
Iteration #32: num_faces=0
Iteration #33: num_faces=0
Iteration #34: num_faces=0
Iteration #35: num_faces=0
Iteration #36: num_faces=0
Iteration #37: num_faces=0
Iteration #38: num_faces=0
Iteration #39: num_faces=0
Iteration #40: num_faces=0
Iteration #41: num_faces=0
Iteration #42: num_faces=0
Iteration #43: num_faces=0
Iteration #44: num_faces=0
Iteration #45: num_faces=0
Iteration #46: num_faces=0
Iteration #47: num_faces=0
Iteration #48: num_faces=0
Iteration #49: num_faces=0
Iteration #50: num_faces=0
Iteration #51: num_faces=0
Iteration #52: num_faces=0
Iteration #53: num_faces=0
Iteration #54: num_faces=0
Iteration #55: num_faces=0
Iteration #56: num_faces=0
Iteration #57: num_faces=0
Iteration #58: num_faces=0
Iteration #59: num_faces=0
Iteration #60: num_faces=0
Iteration #61: num_faces=0
Iteration #62: num_faces=0
Iteration #63: num_faces=0
Iteration #64: num_faces=0
Iteration #65: num_faces=0
Iteration #66: num_faces=0
Iteration #67: num_faces=0
Iteration #68: num_faces=0
Iteration #69: num_faces=0
Iteration #70: num_faces=0
Iteration #71: num_faces=0
Iteration #72: num_faces=0
Iteration #73: num_faces=0
Iteration #74: num_faces=0
Iteration #75: num_faces=0
Iteration #76: num_faces=0
Iteration #77: num_faces=0
Iteration #78: num_faces=0
Iteration #79: num_faces=0
Iteration #80: num_faces=0
Iteration #81: num_faces=0
Iteration #82: num_faces=0
Iteration #83: num_faces=0
Iteration #84: num_faces=0
Iteration #85: num_faces=0
Iteration #86: num_faces=0
Iteration #87: num_faces=0
Iteration #88: num_faces=0
Iteration #89: num_faces=0
Iteration #90: num_faces=0
Iteration #91: num_faces=0
Iteration #92: num_faces=0
Iteration #93: num_faces=0
Iteration #94: num_faces=0
Iteration #95: num_faces=0
Iteration #96: num_faces=1
Iteration #97: num_faces=0
Iteration #98: num_faces=0
Iteration #99: num_faces=1
Iteration #100: num_faces=1
Iteration #101: num_faces=1
Iteration #102: num_faces=0
Iteration #103: num_faces=0
Iteration #104: num_faces=0
Iteration #105: num_faces=1
Iteration #106: num_faces=1
Iteration #107: num_faces=1
Iteration #108: num_faces=0
Iteration #109: num_faces=0
Iteration #110: num_faces=1
Iteration #111: num_faces=0
Iteration #112: num_faces=1
Iteration #113: num_faces=1
Iteration #114: num_faces=1
Iteration #115: num_faces=0
Iteration #116: num_faces=0
Iteration #117: num_faces=0
Iteration #118: num_faces=0
Iteration #119: num_faces=0
Iteration #120: num_faces=0
Iteration #121: num_faces=0
Iteration #122: num_faces=0
Iteration #123: num_faces=1
Iteration #124: num_faces=0
Iteration #125: num_faces=0
Iteration #126: num_faces=0
Iteration #127: num_faces=1
Iteration #128: num_faces=1
Iteration #129: num_faces=1
Iteration #130: num_faces=0
Iteration #131: num_faces=1
Iteration #132: num_faces=0
Iteration #133: num_faces=0
Iteration #134: num_faces=0
Iteration #135: num_faces=0
Iteration #136: num_faces=0
Iteration #137: num_faces=0
Iteration #138: num_faces=0
Iteration #139: num_faces=0
Iteration #140: num_faces=0
Iteration #141: num_faces=0
Iteration #142: num_faces=0
Iteration #143: num_faces=0
Iteration #144: num_faces=0
Iteration #145: num_faces=0
Iteration #146: num_faces=0
Iteration #147: num_faces=0
Iteration #148: num_faces=0
Iteration #149: num_faces=0
Iteration #150: num_faces=0
Iteration #151: num_faces=0
Iteration #152: num_faces=0
Iteration #153: num_faces=0
Iteration #154: num_faces=0
Iteration #155: num_faces=0
Iteration #156: num_faces=0
Iteration #157: num_faces=0
Iteration #158: num_faces=0
Iteration #159: num_faces=0
Iteration #160: num_faces=0
Iteration #161: num_faces=0
Iteration #162: num_faces=0
Iteration #163: num_faces=0
Iteration #164: num_faces=0
Iteration #165: num_faces=0
Iteration #166: num_faces=0
Iteration #167: num_faces=0
Iteration #168: num_faces=0
Iteration #169: num_faces=0
Iteration #170: num_faces=0
Iteration #171: num_faces=0
Iteration #172: num_faces=0
Iteration #173: num_faces=0
Iteration #174: num_faces=0
Iteration #175: num_faces=0
Iteration #176: num_faces=0
Iteration #177: num_faces=0
Iteration #178: num_faces=0
Iteration #179: num_faces=0
Iteration #180: num_faces=0
Iteration #181: num_faces=0
Iteration #182: num_faces=0
Iteration #183: num_faces=0
Iteration #184: num_faces=0
Iteration #185: num_faces=0
Iteration #186: num_faces=0
Iteration #187: num_faces=0
Iteration #188: num_faces=0
Iteration #189: num_faces=0
Iteration #190: num_faces=0
Iteration #191: num_faces=0
Iteration #192: num_faces=0
Iteration #193: num_faces=0
Iteration #194: num_faces=0
Iteration #195: num_faces=0
Iteration #196: num_faces=0
Iteration #197: num_faces=0
Iteration #198: num_faces=0
Iteration #199: num_faces=0
Iteration #200: num_faces=0
Iteration #201: num_faces=0
Iteration #202: num_faces=0
Iteration #203: num_faces=0
Iteration #204: num_faces=0
Iteration #205: num_faces=0
Iteration #206: num_faces=0
Iteration #207: num_faces=0
Iteration #208: num_faces=0
Iteration #209: num_faces=0
Iteration #210: num_faces=0
Iteration #211: num_faces=0
Iteration #212: num_faces=0
Iteration #213: num_faces=0
Iteration #214: num_faces=0
Iteration #215: num_faces=0
Iteration #216: num_faces=0
Iteration #217: num_faces=0
Iteration #218: num_faces=0
Iteration #219: num_faces=0
Iteration #220: num_faces=0
```

Then I press CTRL+C to stop the script

````

^CTraceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 137, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, buf)
OSError: [Errno 14] Bad address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./face_detection_camera.py", line 88, in <module>
    main()
  File "./face_detection_camera.py", line 74, in main
    for i, result in enumerate(inference.run()):
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 76, in run
    yield self._engine.camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 257, in camera_inference
    return self._communicate(request).inference_result
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 187, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 137, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, buf)
KeyboardInterrupt
````

I also tried face_camera_trigger.py
It works as well. 
If I call the Python script from a bash script though it won't work.
Take this snippet as an example.

```
while true; do
    if [ -f /home/pi/failsafe ]; then
        echo "Failsafe turned on!" > exit.log
        break
    fi
    echo $$ > mainShPid.log
    echo "Starting the Python Script"
    echo `date`
    ./face_camera_trigger.py
    wait
    echo "Python Script terminated"
done

```
I got this result

```
Starting the Python Script
Fri 15 Jun 14:18:42 EDT 2018
WARNING:root:LoadModel: Model 'FaceDetection' is already loaded.
Python Script terminated
Starting the Python Script
Fri 15 Jun 14:19:02 EDT 2018
^CTraceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 137, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, buf)
OSError: [Errno 14] Bad address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./face_camera_trigger.py", line 40, in <module>
    main()
  File "./face_camera_trigger.py", line 30, in main
    for result in inference.run():
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 76, in run
    yield self._engine.camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 257, in camera_inference
    return self._communicate(request).inference_result
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 187, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 137, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, buf)
KeyboardInterrupt

```
It says that the model is already loaded and therefore it doesn't take a picture when there's a face.
I also tried to call the `inference.close()` from within with `CameraInference(face_detection.model()) as inference:` without any luck.
```
def main():
    with PiCamera() as camera:
        # Configure camera
        camera.resolution = (1640, 922)# Full Frame, 16:9 (Camera v2)
        camera.start_preview()
        # Do inference on VisionBonnet
        with CameraInference(face_detection.model()) as inference:
            for result in inference.run():
                if len(face_detection.get_faces(result)) >= 1:
                    filename = dt.datetime.now().strftime("%Y-%m-%d_%H.%M.%S.jpg")
                    camera.capture(filename)
                    camera.resolution = (640, 480)
                    camera.start_recording(dt.datetime.now().strftime("%Y-%m-%d_%H.%M.%S.h264"))
                    camera.wait_recording(600)
                    camera.stop_recording()
                    send(filename) # Send the JPG by email.
                    break
            inference.close() #Not working
        camera.stop_preview()
        camera.close()
```
This script also when called from a bash script or as a function called within a Python While loop, it doesn't free the mmal ressources. I will read the doc about that 'with' statement until your next reply. 

EDIT: I fixed the code blocks formatting

**Comment by dmitriykovalev** [comment]
You don't need to call `inference.close()` explicitly because of `with CameraInference(...)` construction. Otherwise it's going to call `inference.close()` twice and the second one would fail.  You also don't need to call `camera.close()` explicitly for the same reason. 

`CameraInference` is a helper class which loads and unloads model: https://github.com/google/aiyprojects-raspbian/blob/e48363018e37b1fdc22d5ddc4b221db97c2cf47b/src/aiy/vision/inference.py#L68

Having `WARNING:root:LoadModel: Model 'FaceDetection' is already loaded.` is fine, that's just a warning.

**Comment by davesdere** [comment]
Thank you Dmitri! I just looked over this bit of code differently because of that conversation.

**Comment by dmitriykovalev** [comment]
@davesdere No problem! Closing this for now.
