### ISSUE TITLE
aiy._drivers._spicomm.SpicommTimeoutError  occurred when i run the face-detection

### ISSUE THREAD

**Issue by sainttelant** [google/aiyprojects-raspbian#408]
Traceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 137, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, buf)
OSError: [Errno 62] Timer expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./face_detection.py", line 51, in <module>
    main()
  File "./face_detection.py", line 37, in main
    with ImageInference(face_detection.model()) as inference:
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 95, in __init__
    self._key = self._engine.load_model(descriptor)
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 201, in load_model
    _check_firmware_info(self.get_firmware_info())
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 275, in get_firmware_info
    info = self._communicate(request).firmware_info
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 187, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 147, in transact
    raise SpicommTimeoutError
aiy._drivers._spicomm.SpicommTimeoutError

**Comment by sainttelant** [comment]
i ran the inferences successfully by typing ./face_detection.py --input face.jpg, however, after i ran the apt-get update,and installed several jpeg relevant devs, it couldn;t be executed,and popped errors like above, anyone knows the reasons? i reboot the devices, but it still had the errors

**Comment by dmitriykovalev** [comment]
@sainttelant Did you run `apt-get update` or `apt-get upgrade`? Does it work fine with our SD card image without any updates?

**Comment by sainttelant** [comment]
@dmitriykovalev ,yes, i did run apt-get update, i found it was fixed up after i replugged sd card in vision kit and rebooted it again
