### ISSUE TITLE
Error testing on Bonnet the compiled binaryproto for transfer learning model

### ISSUE THREAD

**Issue by dvillevald** [google/aiyprojects-raspbian#417]
I followed EXTENSION TO POET TUTORIAL referenced at AIY project website, re-trained mobilenet on my images and compiled the retrained_graph.pb with no (visible) issues on Ubuntu 16.04. However after I uploaded retrained_graph.binaryproto and retrained_labels.txt to Pi and ran (as suggested in step 5):

# On Pi
~/AIY-projects-python/src/examples/vision/mobilenet_based_classifier.py \
  --model_path ~/retrained_graph.binaryproto \
  --label_path ~/retrained_labels.txt \
  --input_height 160 \
  --input_width 160 \
  --input_layer input \
  --output_layer final_result \
  --preview 

I got the following error message:

pi@raspberrypi:~/AIY-projects-python/src/examples/vision $ ~/AIY-projects-python/src/examples/vision/mobilenet_based_classifier.py \
>   --model_path ~/retrained_graph.binaryproto \
>   --label_path ~/retrained_labels.txt \
>   --input_height 160 \
>   --input_width 160 \
>   --input_layer input \
>   --output_layer final_result \
>   --preview
**Traceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 128, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, self._tbuf)
OSError: [Errno 14] Bad address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/examples/vision/mobilenet_based_classifier.py", line 111, in main
    for i, result in enumerate(camera_inference.run()):
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 76, in run
    yield self._engine.camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 257, in camera_inference
    return self._communicate(request).inference_result
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 187, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 143, in transact
    raise SpicommInternalError
aiy._drivers._spicomm.SpicommInternalError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/examples/vision/mobilenet_based_classifier.py", line 130, in main
    'ascii', 'backslashreplace').decode('ascii')
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 87, in __exit__
    self.close()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 79, in close
    self._engine.stop_camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 263, in stop_camera_inference
    self._communicate(request)
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 189, in _communicate
    raise InferenceException(response.status.message)
aiy.vision.inference.InferenceException: StopCameraInference: Camera inference is not running.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/examples/vision/mobilenet_based_classifier.py", line 137, in <module>
    main()
  File "/home/pi/AIY-projects-python/src/examples/vision/mobilenet_based_classifier.py", line 133, in main
    camera.stop_preview()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 758, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 752, in close
    raise exc
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1995, in _control_callback
    "No data recevied from sensor. Check all connections, "
picamera.exc.PiCameraRuntimeError: No data recevied from sensor. Check all connections, including the SUNNY chip on the camera board**

I am attaching my retrained_graph.binaryproto and retrained_labels.txt:
[retrained_graph.zip](https://github.com/google/aiyprojects-raspbian/files/2131116/retrained_graph.zip)

As suggested at https://github.com/google/aiyprojects-raspbian/issues/335 I updated SD card but it did not help to resolve the issue. I also confirmed that it seems to be related to the compiler - when I compiled (unchanged) mobilenet model I got the same error running mobilenet_based_classifier.py as above.

P.S. If it helps - I have no trouble running demos from src/examples/vision

Thank you for looking into this.
Dmitri

**Comment by dmitriykovalev** [comment]
@dvillevald can you please also attach `dmesg` output after everything fails? There is a chance that Myriad crashes on your model for some reason.

**Comment by weiran-work** [comment]
@dvillevald Are you using the latest bonnet_model_compiler?

**Comment by weiran-work** [comment]
@dvillevald 
I tried to run your compiled model on my vision kit. I can run it. It seems like the model is trained to output 2 classes. 

You said when you compile the default mobilenet model, you got similar error as above. It seems to me that your firmware is still outdated. Could you run this command and let us know the output?
dpkg -l aiy*

Also, how did you update the SD card?

**Comment by dvillevald** [comment]
@weiranzhao, @dmitriykovalev  Thanks a lot for helping and pointing out on the probable cause (outdated firmware), much appreciated. I updated SD card image by running

sudo apt-get update; sudo apt-get upgrade; sudo reboot

and it solved the problem so I am closing this issue as resolved.
