### ISSUE TITLE
Error using Vision kit on a clean raspbian setup

### ISSUE THREAD

**Issue by maxritter** [google/aiyprojects-raspbian#420]
Hello,

I am trying to run one of the samples of the AIY vision kit on a clean setup of raspbian.

I was able to install the python library and install all other dependencies.

However, when I try to run an image classification demo, I get the following error:

FileNotFoundError: [Errno 2] No such file or directoy: '/dev/vision_spicomm'

So I expect I am missing some service / driver installation, but where do I get it from?

Thanks,
Max

**Comment by dmitriykovalev** [comment]
@maxritter We are going to release new image with clear instructions how to setup on clean Raspbian. Regarding your error: you need to install appropriate kernel drivers for the VisionKit. You can get the list of installed AIY debian packages by running `dpkg -l | grep -i aiy`.

**Comment by ghost** [comment]
@dmitriykovalev  So I am running into the same issue. In the meantime until the new instruction set comes down, can you point us to where we could obtain the /dev/vision_spicomm files? They weren't present on the included sd card after following the instructions [here](https://aiyprojects.withgoogle.com/help/#updating-your-sd-card).

**Comment by dmitriykovalev** [comment]
@nicknauert `/dev/vision_spicomm` is not a regular file, it is a device node created by `aiy-vision` driver. It is installed by a corresponding `dkms` package which you can see by running `dpkg -l | grep -i aiy`.

**Comment by ghost** [comment]
@dmitriykovalev I see. I appreciate the quick response! Maybe I'll go back through the build install process and see if it corrects itself.

**Comment by manoj7410** [comment]
@nicknauert HACKING.md file has been updated and you can get this file at https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md
This should be helpful in installing AIY packages on clean Raspbian.

**Comment by dmitriykovalev** [comment]
@maxritter Please check new instructions! Closing this one for now.

**Comment by LuwkasLima** [comment]
Hi Guys,

I'm with the exactly same scenario: Trying to run one of the examples of the AIY Vision kit in a clean raspbian setup.

I've followed all the steps and got the following packages installed:

```
aiy-bt-prov-server                    1.0-0                             all          AIY Bluetooth provisioning server
aiy-core                              1.0-0                             all          Core packages for AIY Projects Kits
aiy-dkms                              1.1                               all          Hardware device drivers for AIY
aiy-full                              1.0-0                             all          Full package set for AIY Projects Kits
aiy-gadget                            1.1-0                             all          AIY USB Gadget
aiy-io-mcu-firmware                   1.0-0                             all          AIY MCU Firmware
aiy-misc                              1.0-0                             all          Miscellaneous packages for AIY 
aiy-models                            1.0-0                             all          Binary model data for AIY devices
aiy-overlay-vision                    1.0-0                             all          Device tree overlay for AIY Vision 
aiy-overlay-voice                     1.0-0                             all          Device tree overlay for AIY Voice 
aiy-projects-python                   1.1-0                             all          AIY Python API
aiy-python-wheels                     1.0-0                             all          Prebuilt Python wheels for AIY
aiy-vision-firmware                   1.1-0                             all          Binary firmware for AIY vision  aiy-voice-services                    1.1-0                             all          AIY Voice Services
aiy-voicebonnet-routes                1.0-0                             all          Routing for AIY voicebonnet
aiy-voicebonnet-soundcard-dkms        1.1                               all          Hardware device drivers for 
leds-ktd202x-dkms                     1.1                               all          Hardware device drivers for AIY 
pwm-soft-dkms                         1.1                               all          Hardware device drivers for AIY
```
However, when I run any of the examples, I get the following message:

`FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'`

I've also tried the spicomm_test.py:

```
pi@raspberrypi:~/AIY-voice-kit-python/src/tests $ python3 spicomm_test.py 
EEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_empty_request (__main__.AsyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 43, in test_empty_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 146, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_huge_invalid_request (__main__.AsyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 74, in test_huge_invalid_request
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 146, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request (__main__.AsyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 58, in test_invalid_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 146, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request_force_allocate (__main__.AsyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 69, in test_invalid_request_force_allocate
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 146, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request_timeout (__main__.AsyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 63, in test_invalid_request_timeout
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 146, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_valid_request (__main__.AsyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 48, in test_valid_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 146, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_valid_request_force_allocate (__main__.AsyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 53, in test_valid_request_force_allocate
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 146, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_big_mappings (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 104, in test_big_mappings
    with SpicommDev() as dev:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_empty_request (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 43, in test_empty_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 289, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_huge_invalid_request (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 74, in test_huge_invalid_request
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 289, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 58, in test_invalid_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 289, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request_force_allocate (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 69, in test_invalid_request_force_allocate
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 289, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request_timeout (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 63, in test_invalid_request_timeout
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 289, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_mappings (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 95, in test_mappings
    with SpicommDev() as dev:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_max_mappings (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 124, in test_max_mappings
    with SpicommDev() as dev, \
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_multiple_dev (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 88, in test_multiple_dev
    with SpicommDev() as dev1, SpicommDev() as dev2:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_multiple_map_unmap (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 112, in test_multiple_map_unmap
    with SpicommDev() as dev:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_overlapping_mappings (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 146, in test_overlapping_mappings
    with SpicommDev() as dev:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_same_offset_mappings (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 134, in test_same_offset_mappings
    with SpicommDev() as dev:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_valid_request (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 48, in test_valid_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 289, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_valid_request_force_allocate (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 53, in test_valid_request_force_allocate
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 289, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_zero_length_mapping (__main__.SyncSpicommMmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 118, in test_zero_length_mapping
    with SpicommDev() as dev:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "spicomm_test.py", line 19, in SpicommDev
    dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_empty_request (__main__.SyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 43, in test_empty_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 212, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_huge_invalid_request (__main__.SyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 74, in test_huge_invalid_request
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 212, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request (__main__.SyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 58, in test_invalid_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 212, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request_force_allocate (__main__.SyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 69, in test_invalid_request_force_allocate
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 212, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_invalid_request_timeout (__main__.SyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 63, in test_invalid_request_timeout
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 212, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_valid_request (__main__.SyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 48, in test_valid_request
    with self.Spicomm() as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 212, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

======================================================================
ERROR: test_valid_request_force_allocate (__main__.SyncSpicommTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spicomm_test.py", line 53, in test_valid_request_force_allocate
    with self.Spicomm(default_payload_size=8) as spicomm:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 212, in __init__
    self._dev = os.open(SPICOMM_DEV, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

----------------------------------------------------------------------
Ran 29 tests in 0.026s

FAILED (errors=29)
```

**Comment by geeksville** [comment]
@dmitriykovalev @LuwkasLima I think you should possibly reopen this. It seems to me the underlying problem is that aiy-dkms doesn't have proper triggers set in its deb file to force it to reinstall when the kernel is upgraded.  I suspect @LuwkasLima encountered the same thing I just encountered when I did an "apt-get dist-upgrade".  The raspbian folks updated the kernel, so a new kernel came down (yay) but it didn't rebuild and reinstall the aiy-dkms kernel modules.

@LuwkasLima the workaround I used was "apt-get --reinstall install aiy-dkms" to force it.

**Comment by dmitriykovalev** [comment]
@geeksville You are right, there are issues with current debian packages, we are going to fix this in the next SD card release which should happen pretty soon.

**Comment by geeksville** [comment]
@dmitriykovalev btw your kit is really cool.  I just spent an afternoon yesterday using it to make this twitterbot: [hummingbot](https://twitter.com/hummingbot1).  Photo [here](https://www.thingiverse.com/thing:3195761/files). It worked great and was super easy, if there is any interest I wouldn't mind doing a small writeup.

Keep rocking it!

**Comment by dmitriykovalev** [comment]
@geeksville Thanks! Your project looks very cool! Would be nice if you can describe it at https://www.hackster.io/google/products/aiy-vision

**Comment by geeksville** [comment]
@dmitriykovalev sure thing here you go: https://www.hackster.io/projects/1295f2.  I'm an ex-googler and if you ever do betas on new hw and want other demos I'd love to give it a shot. (sorry for spamming this issue btw ;-) ).

**Comment by RootAculus** [comment]
> @geeksville You are right, there are issues with current debian packages, we are going to fix this in the next SD card release which should happen pretty soon.

@dmitriykovalev My daughter(12 years) is working hard on her Robot Guide Dog which has Aiy-Vision Bonnet. She is experiencing the exact same problem.  

FileNotFoundError: [Errno 2] No such file or directoy: '/dev/vision_spicomm'

She researched online for solutions but no luck at all. She was very happy to find this issue and now she is wondering when the new SD Card release shall be available so she can continue to work on her project :) Thanks

Project Pages:
https://selinoid.wordpress.com/2018/10/11/english-coderdojo-coolest-projects-2018-1/
https://www.raspberrypi.org/blog/coolest-projects-international-2018/

**Comment by dmitriykovalev** [comment]
@geeksville Thanks for sharing your project on Hackster! Unfortunately for now all new hw testing is internal. Please take a look at https://aiyprojects.withgoogle.com/edge-tpu/ by the way :)

**Comment by dmitriykovalev** [comment]
@RootAculus New SD card release is already available https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116  If you are trying to set everything up on the original Raspbian image, please try to follow steps in [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/v20181116/HACKING.md).  

iC4U looks great!

**Comment by dmitriykovalev** [comment]
We have updated our debian packages, please try to follow instructions in [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/v20181116/HACKING.md) and `/dev/vision_spicomm` should be available after installing `aiy-vision-dkms` package.

**Comment by dodysw** [comment]
I must not have done it in the right order, after following HACKING.md (upgrading from August 2018 SD card image release), I had to reinstall the package before `/dev/vision_spicomm` finally appeared.
```
sudo apt install --reinstall aiy-vision-dkms
sudo reboot
```
Thanks for the instructions!

**Comment by RootAculus** [comment]
> @RootAculus New SD card release is already available https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116 If you are trying to set everything up on the original Raspbian image, please try to follow steps in [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/v20181116/HACKING.md).
> 
> iC4U looks great!

@dmitriykovalev Thanks again...

She created a new SD Card with the latest released as you suggested.  This time she received an error message that suggests no camera connection.  She tried the camera(v 2.1) on Rpi 3B+ it worked, then she tried a different cable between bonnet and camera, this time camera is recognized but she received the following error message:

 _"No data recevied from sensor. Check all connections, "
picamera.exc.PiCameraRuntimeError: No data recevied from sensor. Check all connections, including the SUNNY chip on the camera board_

We checked the connections including the one on the camera, everything seems OK. 

Any recommendations?

Thanks!

**Comment by dmitriykovalev** [comment]
@RootAculus Are you trying to run VisionBonnet connected to Pi 3B+ ?  There is an issue here, it doesn't work on 3B+ but it works on 3B if you can find an additional flex cable. Can you try to check that everything works on Pi Zero?

**Comment by RootAculus** [comment]
> @RootAculus Are you trying to run VisionBonnet connected to Pi 3B+ ? There is an issue here, it doesn't work on 3B+ but it works on 3B if you can find an additional flex cable. Can you try to check that everything works on Pi Zero?

@dmitriykovalev  We are trying to use it on Pi Zero(One that comes out with the kit). 
We thought that the camera might be broken so for troubleshooting purposes, we tried the camera(v2.1) on Rpi 3B+, not the Vision Bonnet. :) 

Following message is from VisionBonnet on Pi Zero. (We tried the vision bonnet on different Zeros as well, still got the same error.)

_"No data recevied from sensor. Check all connections, "
picamera.exc.PiCameraRuntimeError: No data recevied from sensor. Check all connections, including the SUNNY chip on the camera board_

**Comment by ScenicSwisscoast** [comment]
same error here:  _FileNotFoundError: [Errno 2] No such file or directoy: '/dev/vision_spicomm_'. 

this is with a brand new pi vision kit out of the box, and I downloaded the version 181116 and flashed it on a sd-card from here https://github.com/google/aiyprojects-raspbian/releases

I don't manage to get any examples in the folder ~/AIY-projects-python/src/examples/vision up and running 

for example: when i run
>sudo python3 face_camera_trigger.py

i get this 
_FileNotFoundError: [Errno 2] No such file or directoy: '/dev/vision_spicomm_'.

**Comment by seth-johnson-sp** [comment]
> same error here: _FileNotFoundError: [Errno 2] No such file or directoy: '/dev/vision_spicomm_'.
> 
> this is with a brand new pi vision kit out of the box, and I downloaded the version 181116 and flashed it on a sd-card from here https://github.com/google/aiyprojects-raspbian/releases
> 
> I don't manage to get any examples in the folder ~/AIY-projects-python/src/examples/vision up and running
> 
> for example: when i run
> 
> > sudo python3 face_camera_trigger.py
> 
> i get this
> _FileNotFoundError: [Errno 2] No such file or directoy: '/dev/vision_spicomm_'.

Same result here. I found that the problem occurs if on first startup I go through the configuration UI and accept the offer to update the software. If I boot from a fresh copy of this image (181116) and choose not to update the Raspbian software, then the AIY vision stuff works. It's the update that triggers the FileNotFoundError: [Errno 2] No such file or directoy: '/dev/vision_spicomm_'. error.

**Comment by weathermanj** [comment]
I am seeing the same as the above. Previously I was running on an older image without issue, I upgraded it to the latest today and now I suffer the same as the others. 

> FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

I have used a new image, and also followed HACKING.md. neither work

**Comment by sdcharle** [comment]
Having similar troubles here in July 2019, bummer! No joy at all.

**Comment by Joseph-Schenkkan** [comment]
Excitedly got my pi zero w up and running with AIY, all working great except when trying to use any of the demos or camera - I get the same error as everyone else here 

FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

Any update on this?
