### ISSUE TITLE
permission denied when trying to open grpc.py

### ISSUE THREAD

**Issue by mra1984** [google/aiyprojects-raspbian#453]
I am getting a 'permission denied' error in terminal when I try to open this file via the file path? 
In python when I run I get this error? 
Any ideas?  Thanks in advance 
Python 3.5.3 (/usr/bin/python3)
>>> %Run grpc.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/auth/transport/grpc.py", line 20, in <module>
    import grpc
  File "/home/pi/Desktop/aiyprojects-raspbian-aiyprojects/src/aiy/assistant/grpc.py", line 18, in <module>
    import aiy.assistant.auth_helpers
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 25, in <module>
    import google_auth_oauthlib.flow
ImportError: No module named 'google_auth_oauthlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/aiyprojects-raspbian-aiyprojects/src/aiy/assistant/grpc.py", line 17, in <module>
    import aiy._apis._speech
  File "/home/pi/AIY-projects-python/src/aiy/_apis/_speech.py", line 27, in <module>
    import google.auth.transport.grpc
  File "/usr/local/lib/python3.5/dist-packages/google/auth/transport/grpc.py", line 23, in <module>
    'gRPC is not installed, please install the grpcio package to use the '
ImportError: gRPC is not installed, please install the grpcio package to use the gRPC transport.

#115

**Comment by manoj7410** [comment]
@mra1984 Have you installed the latest sdcard image from : https://github.com/google/aiyprojects-raspbian/releases ?

**Comment by mra1984** [comment]
yes I installed the latest one posted from this forum at the link you mention

**Comment by dmitriykovalev** [comment]
`/home/pi/Desktop/aiyprojects-raspbian-aiyprojects/src/aiy/assistant/grpc.py` this is not the default path on our SD card image (everything should be in `/home/pi/AIY-projects-python`), can you try the image from Releases page?

**Comment by mra1984** [comment]
I re-ran it on the on the right image in the right location and got the same result?

Python 3.5.3 (/usr/bin/python3)
>>> %cd /home/pi/AIY-projects-python/src/aiy/assistant
>>> %Run grpc.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/auth/transport/grpc.py", line 20, in <module>
    import grpc
  File "/home/pi/AIY-projects-python/src/aiy/assistant/grpc.py", line 18, in <module>
    import aiy.assistant.auth_helpers
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 25, in <module>
    import google_auth_oauthlib.flow
ImportError: No module named 'google_auth_oauthlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/aiy/assistant/grpc.py", line 17, in <module>
    import aiy._apis._speech
  File "/home/pi/AIY-projects-python/src/aiy/_apis/_speech.py", line 27, in <module>
    import google.auth.transport.grpc
  File "/usr/local/lib/python3.5/dist-packages/google/auth/transport/grpc.py", line 23, in <module>
    'gRPC is not installed, please install the grpcio package to use the '
ImportError: gRPC is not installed, please install the grpcio package to use the gRPC transport.
>>>

**Comment by mra1984** [comment]
I have ran pip install grpcio already

**Comment by mra1984** [comment]
I also ran this:
pip install --upgrade google-cloud-speech
