### ISSUE TITLE
aiy.audio.record_to_wave() fails on second invocation

### ISSUE THREAD

**Issue by jfatula** [google/aiyprojects-raspbian#496]
In working with VoiceKit (V1) on a Pi3 using the August 3rd 2018 AIY projects image, I've found that a second call to aiy.audio.record_to_wave() fails with a threading error. As an example, this test code:
```
#!/usr/bin/env python3
import logging
import aiy.audio

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s:%(name)s:%(message)s"
)

def main():
    print('Start first recording...')
    aiy.audio.record_to_wave('test1.wav', 5)
    print('First recording done. Start second recording...')
    aiy.audio.record_to_wave('test2.wav', 5)
    print('Second recording done.')

if __name__ == '__main__':
    main()

```
throws this runtime error on the second call:
```
pi@raspberrypi:~ $ python3 test_record.py
Start first recording...
[2018-09-24 22:54:32,265] INFO:recorder:started recording
First recording done. Start second recording...
Traceback (most recent call last):
  File "test_record.py", line 18, in <module>
    main()
  File "test_record.py", line 14, in main
    aiy.audio.record_to_wave('test2.wav', 5)
  File "/opt/aiy/projects-python/src/aiy/audio.py", line 92, in record_to_wave
    with recorder, dumper:
  File "/opt/aiy/projects-python/src/aiy/_drivers/_recorder.py", line 144, in __enter__
    self.start()
  File "/usr/lib/python3.5/threading.py", line 840, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```
Until an official patch is available, for my limited needs I'm using the following substitute as a temporary workaround to explicitly reinstantiate the recorder driver at each call:
```
import aiy.audio
import aiy._drivers._recorder
import time
...
def my_record_to_wave(filepath, duration):
    recorder = aiy._drivers._recorder.Recorder()
    dumper = aiy.audio._WaveDump(filepath, duration)
    with recorder, dumper:
        recorder.add_processor(dumper)
        while not dumper.is_done():
            time.sleep(0.1)

```

-jon
```

**Comment by dmitriykovalev** [comment]
There is a new experimental Audio API in [voice/audio.py](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/aiy/voice/audio.py) now.
