### ISSUE TITLE
error completing check cloud script, exception in speech request

### ISSUE THREAD

**Issue by AvivaShooman** [google/aiyprojects-raspbian#501]
I am using the v1 voice kit, raspberry pi 3 and have looked all over for solutions online. I reinstalled the image, updated and upgraded all the files on the raspberry pi. I git pulled for the latest version of google aiy kit software. I checked my billing settings and made sure that they are linked to my project. However, I am still getting this error. 

"Testing the Google Cloud Speech API...
Traceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_apis/_speech.py", line 266, in do_request
    service = self._make_service(self._channel_factory.make_channel())
  File "/opt/aiy/projects-python/src/aiy/_apis/_speech.py", line 83, in make_channel
    self._credentials.refresh(request)
  File "/usr/local/lib/python3.5/dist-packages/google/oauth2/service_account.py", line 310, in refresh
    request, self._token_uri, assertion)
  File "/usr/local/lib/python3.5/dist-packages/google/oauth2/_client.py", line 143, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python3.5/dist-packages/google/oauth2/_client.py", line 109, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/usr/local/lib/python3.5/dist-packages/google/oauth2/_client.py", line 59, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.', '{\n  "error": "invalid_grant",\n  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems."\n}')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/checkpoints/check_cloud.py", line 104, in <module>
    main()
  File "/home/pi/AIY-projects-python/checkpoints/check_cloud.py", line 95, in main
    if not check_speech_reco():
  File "/home/pi/AIY-projects-python/checkpoints/check_cloud.py", line 68, in check_speech_reco
    output = req.do_request()
  File "/opt/aiy/projects-python/src/aiy/_apis/_speech.py", line 279, in do_request
    raise Error('Exception in speech request') from exc"

**Comment by jfatula** [comment]
You might want to use:
`pi@raspberrypi:~ $ timedatectl status
`
to check that your system clock is synchronized with NTP and that your timezone setting is correct.

**Comment by dmitriykovalev** [comment]
Please try [new SD card image](https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116), `check_cloud.py` was updated.
