### ISSUE TITLE
Unable to run assistant_grpc_demo

### ISSUE THREAD

**Issue by fdemberla** [google/aiyprojects-raspbian#531]
Traceback (most recent call last):
  File "/usr/local/bin/assistant_grpc_demo.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/aiy/projects-python/src/examples/voice/assistant_grpc_demo.py", line 20, in <module>
    import aiy.assistant.grpc
  File "/opt/aiy/projects-python/src/aiy/assistant/grpc.py", line 17, in <module>
    import aiy._apis._speech
  File "/opt/aiy/projects-python/src/aiy/_apis/_speech.py", line 39
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

PLEASE HELP

**Comment by fdemberla** [comment]
had to install the NEWEST release of all the OS
