### ISSUE TITLE
Vision V1 button error: Failed to add edge detection

### ISSUE THREAD

**Issue by dvillevald** [google/aiyprojects-raspbian#569]
Hello, I have a trouble running examples with **BUTTON_GPIO_PIN** (e.g. button_example.py) on Vision kit V1 after updating the system image to 2018-11-16. Here is an error I am getting:

`pi@raspberrypi:~/AIY-projects-python/src/examples/gpiozero $ ./button_example.py `
Traceback (most recent call last):
  File "./button_example.py", line 19, in <module>
    button = Button(BUTTON_GPIO_PIN)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 303, in __init__
    pin, pull_up, bounce_time, pin_factory=pin_factory
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 338, in __init__
    super(HoldMixin, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 100, in __init__
    self.pin.when_changed = self._fire_events
  File "/usr/lib/python3/dist-packages/gpiozero/pins/__init__.py", line 388, in <lambda>
    lambda self, value: self._set_when_changed(value),
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 289, in _set_when_changed
    self._enable_event_detect()
  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 219, in _enable_event_detect
    bouncetime=self._bounce)
RuntimeError: Failed to add edge detection
 
Thank you for helping.

**Comment by dmitriykovalev** [comment]
That's probably because of an issue in [RPi.GPIO](https://pypi.org/project/RPi.GPIO/) library.  Can you try to downgrade to version 0.6.3?
