### ISSUE TITLE
Unable to install Python Library on RPi Zero W running Raspbian Stretch

### ISSUE THREAD

**Issue by aadibajpai** [google/aiyprojects-raspbian#585]
I'm following [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md) to set up the Vision kit after a clean flash to Stretch.

All steps were successful until `sudo pip3 install -e AIY-projects-python/src`

Output ->

```
pi@raspberrypi:~ $ sudo pip3 install -e AIY-projects-python/src
Obtaining file:///home/pi/AIY-projects-python/src
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from aiy-projects-python==1.2)
Collecting google-assistant-grpc==0.2.0 (from aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/d3/3c/4a44b54b196fb7f23335f17fdfd3ce477cbff2404324df2ef9ef1f3e4bd3/google_assistant_grpc-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: google-assistant-library==1.0.1 in /usr/local/lib/python3.5/dist-packages-linux-armv6l (from aiy-projects-python==1.2)
Collecting google-auth-oauthlib==0.2.0 (from aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/46/df/d1f94ee2cffe5a83721f262efe51f3b2dcdd3b616caf007b8490e824c550/google_auth_oauthlib-0.2.0-py2.py3-none-any.whl
Collecting google-auth==1.5.1 (from aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/58/cb/96dbb4e50e7a9d856e89cc9c8e36ab1055f9774f7d85f37e2156c1d79d9f/google_auth-1.5.1-py2.py3-none-any.whl
Collecting google-cloud-speech==0.36.0 (from aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/9a/a4/49b8e7b6b89facc17e554abe6aa401e01e076b64f79745e666460a8d5bd6/google_cloud_speech-0.36.0-py2.py3-none-any.whl
Requirement already satisfied: gpiozero in /usr/lib/python3/dist-packages (from aiy-projects-python==1.2)
Collecting paho-mqtt (from aiy-projects-python==1.2)
  Using cached https://www.piwheels.org/simple/paho-mqtt/paho_mqtt-1.4.0-py3-none-any.whl
Requirement already satisfied: picamera in /usr/lib/python3/dist-packages (from aiy-projects-python==1.2)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from aiy-projects-python==1.2)
Requirement already satisfied: protobuf==3.6.1 in /usr/local/lib/python3.5/dist-packages (from aiy-projects-python==1.2)
Collecting grpcio>=1.3.5 (from google-assistant-grpc==0.2.0->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/e3/aa/6ee1f1c0b35d270725abff07f8d807c0413154af14cd019fd3aa3ab69d64/grpcio-1.19.0.tar.gz
Collecting googleapis-common-protos>=1.5.2 (from google-assistant-grpc==0.2.0->aiy-projects-python==1.2)
  Using cached https://www.piwheels.org/simple/googleapis-common-protos/googleapis_common_protos-1.5.8-py3-none-any.whl
Collecting requests<3,>=2.14.2 (from google-assistant-library==1.0.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting argparse<2,>=1.4.0 (from google-assistant-library==1.0.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting pathlib2<3,>=2.3.0 (from google-assistant-library==1.0.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Collecting enum34<2,>=1.1.6 (from google-assistant-library==1.0.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/lib/python3/dist-packages (from google-auth-oauthlib==0.2.0->aiy-projects-python==1.2)
Collecting rsa>=3.1.4 (from google-auth==1.5.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth==1.5.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/da/98/8ddd9fa4d84065926832bcf2255a2b69f1d03330aa4d1c49cc7317ac888e/pyasn1_modules-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3.5/dist-packages (from google-auth==1.5.1->aiy-projects-python==1.2)
Collecting cachetools>=2.0.0 (from google-auth==1.5.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whlCollecting google-api-core[grpc]<2.0.0dev,>=0.1.4 (from google-cloud-speech==0.36.0->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/55/8d/02cd1468659994a39b1aced38fecb06885c988d79aaafd8d456d09571871/google_api_core-1.8.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf==3.6.1->aiy-projects-python==1.2)
Collecting urllib3<1.25,>=1.21.1 (from requests<3,>=2.14.2->google-assistant-library==1.0.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3,>=2.14.2->google-assistant-library==1.0.1->aiy-projects-python==1.2)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests<3,>=2.14.2->google-assistant-library==1.0.1->aiy-projects-python==1.2)
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

Please let me know if something more is needed.
Thank you.

**Comment by aadibajpai** [comment]
tried again and worked except getting stuck at building wheels for grpcio.
Did that separately by pip install grpcio and then tried again and worked fine 👍
