### ISSUE TITLE
[Errno 2] No such file or directory: '/sys/bus/i2c/drivers/aiy-io-i2c/1-0051/gpio-aiy-io/gpio'

### ISSUE THREAD

**Issue by Geershift** [google/aiyprojects-raspbian#598]
I've modified the code from Aallen's article https://medium.com/@aallan/the-do-you-think-he-saurs-f1fdbc8846de to run a second servo for tilt and after fixing some outdated module locations I've come across this error when trying to run the code

`Traceback (most recent call last):
  File "./facetrackaiy.py", line 11, in <module>
    from aiy.pins import PIN_A
  File "/opt/aiy/projects-python/src/aiy/pins.py", line 62, in <module>
    _PIN_OFFSET = _detect_gpio_offset(_MODULE_PATH)
  File "/opt/aiy/projects-python/src/aiy/pins.py", line 27, in _detect_gpio_offset
    for folder in listdir(module_path):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/bus/i2c/drivers/aiy-io-i2c/1-0051/gpio-aiy-io/gpio'
`
I've re-imaged, run update and upgrade, uncommented some i2c related lines in the /boot/config.txt file and run through every other fix for vaguely similar Errno 2 problems on google search but nothing seems to fix this. The actual directory that _detect_gpio_offset calls also seems to be empty if that helps any

**Comment by manoj7410** [comment]
Can you reflash the board with latest AIY build which is available at https://github.com/google/aiyprojects-raspbian/releases/tag/v20191113 and see if that resolves the issue? I personally haven't tested the link mentioned in above comment but have successfully run 2 servos together.
