### ISSUE TITLE
Having trouble with booting Vision Bonnet, Error Code: -113

### ISSUE THREAD

**Issue by OGHaagan-Daz** [google/aiyprojects-raspbian#623]
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.71+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1145 Fri Sep 21 15:06:38 BST 2018
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Zero W Rev 1.1
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 8 MiB at 0x17400000
[    0.000000] On node 0 totalpages: 98304
[    0.000000] free_area_init_node: node 0, pgdat c09c2630, node_mem_map d7c89c00
[    0.000000]   Normal zone: 864 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 98304 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 97440
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:DA:51:26 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=83f50e63-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 370284K/393216K available (6431K kernel code, 587K rwdata, 1988K rodata, 436K init, 673K bss, 14740K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xd8800000 - 0xff800000   ( 624 MB)
                   lowmem  : 0xc0000000 - 0xd8000000   ( 384 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0xc0008000 - 0xc064fed0   (6432 kB)
                     .init : 0xc08cd000 - 0xc093a000   ( 436 kB)
                     .data : 0xc093a000 - 0xc09ccfe0   ( 588 kB)
                      .bss : 0xc09d28f0 - 0xc0a7ae6c   ( 674 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 24110 entries in 71 pages
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000030] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000062] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000146] bcm2835: system timer (irq = 27)
[    0.000734] Console: colour dummy device 80x30
[    0.000761] console [tty1] enabled
[    0.000796] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060292] pid_max: default: 32768 minimum: 301
[    0.060797] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.060817] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.062097] Disabling memory control group subsystem
[    0.062257] CPU: Testing write buffer coherency: ok
[    0.063380] Setting up static identity map for 0x8200 - 0x8238
[    0.064603] devtmpfs: initialized
[    0.074049] random: get_random_u32 called from bucket_table_alloc+0x88/0x1c4 with crng_init=0
[    0.075038] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.075414] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.075461] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.076791] pinctrl core: initialized pinctrl subsystem
[    0.078095] NET: Registered protocol family 16
[    0.081176] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.087520] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.087537] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.087661] Serial: AMBA PL011 UART driver
[    0.090521] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.091265] uart-pl011 20201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.131244] bcm2835-dma 20007000.dma: DMA legacy API manager at d880d000, dmachans=0x1
[    0.133431] SCSI subsystem initialized
[    0.133653] usbcore: registered new interface driver usbfs
[    0.133747] usbcore: registered new interface driver hub
[    0.133955] usbcore: registered new device driver usb
[    0.140800] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-09-21 15:48
[    0.142886] clocksource: Switched to clocksource timer
[    0.228966] VFS: Disk quotas dquot_6.6.0
[    0.229089] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.229383] FS-Cache: Loaded
[    0.229714] CacheFiles: Loaded
[    0.246567] NET: Registered protocol family 2
[    0.247758] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.247845] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.247940] TCP: Hash tables configured (established 4096 bind 4096)
[    0.248089] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.248120] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.248470] NET: Registered protocol family 1
[    0.249197] RPC: Registered named UNIX socket transport module.
[    0.249209] RPC: Registered udp transport module.
[    0.249214] RPC: Registered tcp transport module.
[    0.249219] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.251265] hw perfevents: no irqs for PMU, sampling events not supported
[    0.251337] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    0.255079] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.267085] FS-Cache: Netfs 'nfs' registered for caching
[    0.268384] NFS: Registering the id_resolver key type
[    0.268436] Key type id_resolver registered
[    0.268444] Key type id_legacy registered
[    0.268470] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.273302] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.273726] io scheduler noop registered
[    0.273739] io scheduler deadline registered (default)
[    0.274261] io scheduler cfq registered
[    0.274275] io scheduler mq-deadline registered
[    0.274282] io scheduler kyber registered
[    0.276579] BCM2708FB: allocated DMA memory 57500000
[    0.276644] BCM2708FB: allocated DMA channel 0 @ d880d000
[    0.284767] Console: switching to colour frame buffer device 82x26
[    0.292686] bcm2835-rng 20104000.rng: hwrng registered
[    0.293016] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    0.294066] vc-sm: Videocore shared memory driver
[    0.294668] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    0.313090] brd: module loaded
[    0.324865] loop: module loaded
[    0.324889] Loading iSCSI transport class v2.0-870.
[    0.325740] usbcore: registered new interface driver smsc95xx
[    0.325772] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.325943] dwc_otg: FIQ enabled
[    0.325950] dwc_otg: NAK holdoff enabled
[    0.325956] dwc_otg: FIQ split-transaction FSM enabled
[    0.325973] Module dwc_common_port init
[    0.326413] usbcore: registered new interface driver usb-storage
[    0.326820] mousedev: PS/2 mouse device common for all mice
[    0.326881] IR NEC protocol handler initialized
[    0.326889] IR RC5(x/sz) protocol handler initialized
[    0.326894] IR RC6 protocol handler initialized
[    0.326899] IR JVC protocol handler initialized
[    0.326904] IR Sony protocol handler initialized
[    0.326909] IR SANYO protocol handler initialized
[    0.326915] IR Sharp protocol handler initialized
[    0.326920] IR MCE Keyboard/mouse protocol handler initialized
[    0.326925] IR XMP protocol handler initialized
[    0.328181] bcm2835-wdt 20100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.328708] bcm2835-cpufreq: min=700000 max=1000000
[    0.329332] sdhci: Secure Digital Host Controller Interface driver
[    0.329342] sdhci: Copyright(c) Pierre Ossman
[    0.329938] mmc-bcm2835 20300000.mmc: could not get clk, deferring probe
[    0.330530] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
[    0.330714] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.331220] ledtrig-cpu: registered to indicate activity on CPUs
[    0.331365] hidraw: raw HID events driver (C) Jiri Kosina
[    0.331595] usbcore: registered new interface driver usbhid
[    0.331604] usbhid: USB HID core driver
[    0.332512] vchiq: vchiq_init_state: slot_zero = d7580000, is_master = 0
[    0.334510] [vc_sm_connected_init]: start
[    0.344073] [vc_sm_connected_init]: end - returning 0
[    0.345022] Initializing XFRM netlink socket
[    0.345085] NET: Registered protocol family 17
[    0.345255] Key type dns_resolver registered
[    0.347039] registered taskstats version 1
[    0.355374] uart-pl011 20201000.serial: cts_event_workaround enabled
[    0.355521] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.358447] mmc-bcm2835 20300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.358466] mmc-bcm2835 20300000.mmc: DMA channel allocated
[    0.416396] sdhost: log_buf @ d7510000 (57510000)
[    0.452670] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.454396] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.456099] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.459142] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.499894] random: fast init done
[    0.502942] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.524309] of_cfs_init
[    0.524441] of_cfs_init: OK
[    0.525455] Waiting for root device PARTUUID=83f50e63-02...
[    0.568777] NOHZ: local_softirq_pending 40
[    0.570704] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.572578] NOHZ: local_softirq_pending 40
[    0.573252] mmc0: new high speed SDHC card at address 59b4
[    0.574095] mmcblk0: mmc0:59b4 SD    7.36 GiB
[    0.576076] NOHZ: local_softirq_pending 40
[    0.576361]  mmcblk0: p1 p2
[    0.590474] mmc1: new high speed SDIO card at address 0001
[    0.596861] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    0.596968] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    0.598324] devtmpfs: mounted
[    0.600726] Freeing unused kernel memory: 436K
[    0.600736] This architecture does not have kernel memory protection.
[    1.078919] systemd[1]: System time before build time, advancing clock.
[    1.242457] NET: Registered protocol family 10
[    1.244390] Segment Routing with IPv6
[    1.266821] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.291746] random: systemd: uninitialized urandom read (16 bytes read)
[    1.300627] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.301673] systemd[1]: Detected architecture arm.
[    1.303415] systemd[1]: Set hostname to <-1002>.
[    1.375057] random: systemd: uninitialized urandom read (16 bytes read)
[    1.611797] random: systemd-sysv-ge: uninitialized urandom read (16 bytes read)
[    2.162947] NOHZ: local_softirq_pending 02
[    2.459224] systemd[1]: Listening on Syslog Socket.
[    2.461438] systemd[1]: Created slice System Slice.
[    2.467423] systemd[1]: Mounting RPC Pipe File System...
[    2.471364] systemd[1]: Created slice system-autologin.slice.
[    2.472393] systemd[1]: Listening on udev Control Socket.
[    2.483748] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.485461] systemd[1]: Created slice User and Session Slice.
[    3.118111] i2c /dev entries driver
[    3.131840] pwm_soft: loading out-of-tree module taints kernel.
[    3.132793] SoftPWM v0.1 initializing.
[    3.132807] Clock resolution is 1ns
[    3.133022] SoftPWM initialized.
[    4.830023] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    5.415721] systemd-journald[61]: Received request to flush runtime journal from PID 1
[    8.546541] dwc2 20980000.usb: 20980000.usb supply vusb_d not found, using dummy regulator
[    8.546681] dwc2 20980000.usb: 20980000.usb supply vusb_a not found, using dummy regulator
[    9.033142] dwc2 20980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    9.034377] dwc2 20980000.usb: DWC OTG Controller
[    9.034442] dwc2 20980000.usb: new USB bus registered, assigned bus number 1
[    9.034521] dwc2 20980000.usb: irq 33, io mem 0x20980000
[    9.048923] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    9.048946] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    9.048958] usb usb1: Product: DWC OTG Controller
[    9.048969] usb usb1: Manufacturer: Linux 4.14.71+ dwc2_hsotg
[    9.048979] usb usb1: SerialNumber: 20980000.usb
[    9.050180] hub 1-0:1.0: USB hub found
[    9.050285] hub 1-0:1.0: 1 port detected
[    9.167469] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    9.195472] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    9.195929] usbcore: registered new interface driver brcmfmac
[    9.661792] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    9.664259] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.39 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-10-23 03:47:14
[   14.087995] uart-pl011 20201000.serial: no DMA platform data
[   14.536010] using random self ethernet address
[   14.536031] using random host ethernet address
[   14.984441] usb0: HOST MAC d2:63:0a:13:c2:16
[   14.985149] usb0: MAC 12:7a:59:c0:2a:5a
[   14.985588] dwc2 20980000.usb: bound driver configfs-gadget
[   15.289552] IPv6: ADDRCONF(NETDEV_UP): usb0: link is not ready
[   17.521422] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   18.911099] Bluetooth: Core ver 2.22
[   18.911202] NET: Registered protocol family 31
[   18.911209] Bluetooth: HCI device and connection manager initialized
[   18.911233] Bluetooth: HCI socket layer initialized
[   18.911247] Bluetooth: L2CAP socket layer initialized
[   18.911285] Bluetooth: SCO socket layer initialized
[   18.962449] Bluetooth: HCI UART driver ver 2.3
[   18.962465] Bluetooth: HCI UART protocol H4 registered
[   18.962471] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   19.002773] Bluetooth: HCI UART protocol Broadcom registered
[   19.798751] aiy-vision spi0.0: Initializing
**[   19.921067] aiy-vision spi0.0: Failed to bind reset GPIO**
[   20.103370] aiy-vision spi0.0: Initializing
**[   20.106996] aiy-vision spi0.0: Failed to bind reset GPIO**
[   20.177283] aiy-io-i2c 1-0051: Setting board type vision
[   20.177892] aiy-io-i2c 1-0051: Driver loaded
[   20.178170] aiy-vision spi0.0: Initializing
**[   20.190504] aiy-vision spi0.0: Failed to bind reset GPIO**
[   20.266884] random: crng init done
[   20.266903] random: 7 urandom warning(s) missed due to ratelimiting
[   20.578711] ktd202x 1-0030: Driver loaded for a ktd2026.
[   20.578998] aiy-vision spi0.0: Initializing
**[   20.587665] aiy-vision spi0.0: Failed to bind reset GPIO**
[   21.926768] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   21.926782] Bluetooth: BNEP filters: protocol multicast
[   21.926805] Bluetooth: BNEP socket layer initialized
[   22.237061] Bluetooth: RFCOMM TTY layer initialized
[   22.237092] Bluetooth: RFCOMM socket layer initialized
[   22.237124] Bluetooth: RFCOMM ver 1.11
[   22.754205] pwm-aiy-io pwm-aiy-io: Driver loaded
[   22.754486] aiy-vision spi0.0: Initializing
**[   22.760085] aiy-vision spi0.0: Failed to bind reset GPIO**
[   23.788645] gpio-aiy-io gpio-aiy-io: Driver loaded
[   23.789027] aiy-vision spi0.0: Initializing
[   23.790227] aiy-adc aiy-adc: Vision bonnet ADC configuration.
[   23.801468] aiy-adc aiy-adc: Driver loaded
[   23.803502] aiy-vision spi0.0: Resetting myriad on probe
[   24.146250] aiy-vision spi0.0: Resetting myriad
[   25.214035] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   25.214053] brcmfmac: power management disabled
[   26.243000] aiy-vision spi0.0: Writing myriad firmware
[   26.713833] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   30.913804] aiy-vision spi0.0: Myriad booting
**[   35.923001] aiy-vision spi0.0: Slave not ready after 5000 ms**
**[   35.923019] aiy-vision spi0.0: Myriad did not boot in a timely fashion**
**[   35.924325] aiy-vision spi0.0: Initial bonnet boot failed: -113**
**[   35.928268] aiy-vision: probe of spi0.0 failed with error -113**
[   44.112836] fuse init (API version 7.26)

I ran "demsg" upon booting up the kit, I've bolded what I'm struggling with. The strange thing is, the console is telling me the bonnet didn't boot properly, but I can still go through the connection process (ssh) through the AIY app. All the files are there (at least I think they are) Afterwards, I ran "i2cdetect -y 1" and this was the result:

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: UU -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- UU -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: 60 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

I noticed from another help post that I'm missing a "61" in the "2" column, not sure what that means, or if it's good/bad, but I am missing it (if I'm supposed to have it.) I haven't edited any of the boot files except to change the host name of the RPi and the login password, I don't think those could be relevant to my issue. It should be noted that my knowledge of Raspberry Pi is the result of 2 days googling, aka, I'm not very familiar with this stuff. I found this issue as I was getting issues trying to run the demos, and after stopping the joy detector (and stopping it from running at startup), every time it would say something along the lines of this:

mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 456, in _init_camera
    self._camera = mo.MMALCamera()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2279, in __init__
    super(MMALCamera, self).__init__()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 633, in __init__
    prefix="Failed to create MMAL component %s" % self.component_type)
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.ril.camera': Out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./face_detection_camera.py", line 78, in <module>
    main()
  File "./face_detection_camera.py", line 47, in main
    with PiCamera(sensor_mode=4, resolution=(1640, 1232), framerate=30) as camera:
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 431, in __init__
    self._init_camera(camera_num, stereo_mode, stereo_decimate)
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 460, in _init_camera
    "Camera is not enabled. Try running 'sudo raspi-config' "
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled. 

Annoyingly, I have enabled the camera interface through the config menu, and allowed it to reboot, and have repeated that step several times to make sure I didn't mess up. Just prior to writing I ran that again, and rebooted. Still no dice.

It shouldn't be a hardware issue, unlike other problems I've looked through, I bought the complete kit, RPi 0 and everything. I'm going to assume I assembled it correctly, if not then I'll be angry that I'm that retarded.

It shouldn't be a software issue (but must be), when initially setting it up, I nabbed the latest version of the OS from the GitHub page and flashed it using Etcher. Prior to writing this, I updated the RPi using "sudo apt-get update" and "sudo apt-get upgrade".

**Comment by OGHaagan-Daz** [comment]
Oh. My. God. 

I AM RETARDED.

>:|

Fuken camera wasn't installed correctly. I hate myself.
