### ISSUE TITLE
unknown locale in AIY-projects-python/src/examples/voice/assistant_grpc_demo.py

### ISSUE THREAD

**Issue by nebucaz** [google/aiyprojects-raspbian#637]
When trying to run the demo 
~/AIY-projects-python/src/examples/voice/assistant_grpc_demo.py

Language can not be determined:

Traceback (most recent call last):
  File "voice/assistant_grpc_demo.py", line 57, in <module>
    main()
  File "voice/assistant_grpc_demo.py", line 42, in main
    parser.add_argument('--language', default=locale_language())
  File "voice/assistant_grpc_demo.py", line 34, in locale_language
    language, _ = locale.getdefaultlocale()
  File "/usr/lib/python3.5/locale.py", line 558, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Locale on system ist set as follows (out of the box)

$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by nebucaz** [comment]
If you are remotely connected to the machine over ssh (eg from a macosx device) you need to set these variables on the machine you are connecting from

add the following to ~/.bash_profile

```
#fix for locale issues when connecting to ubuntu servers
export LANG="en_US.utf8"
export LANGUAGE="en_US.utf8"
export LC_ALL="en_US.utf8"
```
