### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/googleassistant/credentials.json'

### ISSUE THREAD

**Issue by Trancez15** [google/aiyprojects-raspbian#651]
this is the command in this -> (env) pi@raspberrypi:~ $ 
google-oauthlib-tool --client-secrets ~/googleassistant/credentials.json \
--scope https://www.googleapis.com/auth/assistant-sdk-prototype \
--scope https://www.googleapis.com/auth/gcm \
--save --headless

this is the error:
Traceback (most recent call last):
  File "/home/pi/env/bin/google-oauthlib-tool", line 8, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/google_auth_oauthlib/tool/__main__.py", line 100, in main
    scopes=scope
  File "/home/pi/env/lib/python3.5/site-packages/google_auth_oauthlib/flow.py", line 196, in from_client_secrets_file
    with open(client_secrets_file, 'r') as json_file:
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/googleassistant/credentials.json'

How can i fix it?

**Comment by manoj7410** [comment]
Which demo are you trying to run and from where are you following the instructions ?

**Comment by Trancez15** [comment]
I’m following this website: https://pimylifeup.com/raspberry-pi-google-assistant/

**Comment by manoj7410** [comment]
If you are still facing any issue then it is recommended to follow the instructions from https://aiyprojects.withgoogle.com/voice/ which is the official website of AIY projects.
