### ISSUE TITLE
Error when executing src/examples/voice/assistant_grpc_demo.py 

### ISSUE THREAD

**Issue by vishwapinnawala** [google/aiyprojects-raspbian#658]
newbie here Help!!! Tried Re enabling Assistant API and i tried installing AIY os again and again 3 times no luck 

Traceback (most recent call last):
  File "src/examples/voice/assistant_grpc_demo.py", line 57, in <module>
    main()
  File "src/examples/voice/assistant_grpc_demo.py", line 49, in main
    language_code=args.language)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/grpc.py", line 258, in __init__
    super().__init__(language_code, volume_percentage)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/grpc.py", line 94, in __init__
    credentials = auth_helpers.get_assistant_credentials()
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 151, in get_assistant_credentials
    return _try_to_get_credentials(credentials_file)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 123, in _try_to_get_credentials
    credentials = _credentials_flow_interactive(client_secrets)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 75, in _credentials_flow_interactive
    webbrowser.register('chromium-browser', None, webbrowser.Chrome('chromium-browser'), -1)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given

**Comment by manoj7410** [comment]
@vishwapinnawala Which version of voice kit do you have ?
Have you reflashed the kit with the image provided at https://github.com/google/aiyprojects-raspbian/releases/tag/v20191113 ?

**Comment by vishwapinnawala** [comment]
V2 yes i tried reflashing several times and nothing seems to work

**Comment by OrangePeelr** [comment]
I'm getting an identical error with voice kit v1. I also tried reflashing the image with no success.

**Comment by OrangePeelr** [comment]
I fixed the error for my setup with the Raspberry Pi 3B with AIY Voice Kit v1. In the file "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py",  I changed the last argument in webbrowser.register() (line 75) from "-1" to "preferred=True".

Here is the [documentation](https://docs.python.org/3/library/webbrowser.html#webbrowser.register) that explains the options for webbrowser.register(). It looks like in Python 3.7, the webbrowser.register() "preferred" argument only takes keywords now.

Here is the [full, edited file](https://drive.google.com/file/d/0B8AGLT2g1qZ2aXpOeFdGbTJRU1dzY3c0R0VuWDFsZXNibzdR/view?usp=sharing). GitHub wouldn't let me upload the file directly, so the file is on Google Drive.

Or, if you just want to edit the code directly, here is the new code for line 75 in the file "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py":
`        webbrowser.register('chromium-browser', None, webbrowser.Chrome('chromium-browser'), preferred=True)`
(Make sure to leave the spaces from the original line of code in front of the new code segment as spacing matters in Python).

Please let me know if it works or not, or if you have any questions.

**Comment by stevesss** [comment]
The above solved the problem of opening the browser and authenticating the voice kit as it takes me to the web page that says the process is complete, but then the next time I do "assistant_grpc_demo.py" again, it just starts this authentication process all over again instead of starting up  like it is supposed to. (I had it working before.) I am stuck at this point for now.

**Comment by vishwapinnawala** [comment]
i've removed and got alexapi installed so i gived it up😁

**Comment by OrangePeelr** [comment]
> The above solved the problem of opening the browser and authenticating the voice kit as it takes me to the web page that says the process is complete, but then the next time I do "assistant_grpc_demo.py" again, it just starts this authentication process all over again instead of starting up like it is supposed to. (I had it working before.) I am stuck at this point for now.

I'm sorry to hear that stevesss. I just reflashed the image, created a new Google Cloud project and edited the auth_helpers.py file without success in replicating your problem. What Raspberry Pi and Voice Kit version are you using? I know it is a long process, but you might want to try reflashing your image.

**Comment by d3acon** [comment]
Editing auth_helpers.py solved it for me too. But I get a seg fault, once I did the authorisation in the browser.

**Comment by mcmanus-git** [comment]
I'm having the same issue as @d3acon

**Comment by OrangePeelr** [comment]
I get a segmentation fault as well for every file except "assistant_grpc_demo.py"

**Comment by d3acon** [comment]
I opened a new ticket for the seg fault, as this one is for the python problem.

**Comment by 2000prasanth** [comment]
please check i have written a blog on all error that i have encountered
https://2000prasanth.wixsite.com/website/blog/aiy-voice-how-i-set-up-my-voice-kit-amid-errors-my-first-raspberry-pi-project

**Comment by downeyjar** [comment]
Traceback (most recent call last):
  File "/home/pi/AIY-voice-kit-python/src/examples/voice/assistant_grpc_demo.py", line 57, in <module>
    main()
  File "/home/pi/AIY-voice-kit-python/src/examples/voice/assistant_grpc_demo.py", line 49, in main
    language_code=args.language)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/grpc.py", line 258, in __init__
    super().__init__(language_code, volume_percentage)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/grpc.py", line 94, in __init__
    credentials = auth_helpers.get_assistant_credentials()
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 151, in get_assistant_credentials
    return _try_to_get_credentials(credentials_file)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 123, in _try_to_get_credentials
    credentials = _credentials_flow_interactive(client_secrets)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 75, in _credentials_flow_interactive
    webbrowser.register('chromium-browser', None, webbrowser.Chrome('chromium-browser'), -1)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given

I am using raspberry pi 4

**Comment by 2000prasanth** [comment]
i had the same error
pleasw try this

I fixed the error for my setup with the Raspberry Pi 3B with AIY Voice Kit
v1. In the file
"/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", I changed
the last argument in webbrowser.register() (line 75) from "-1" to
"preferred=True".

Here is the documentation
<https://docs.python.org/3/library/webbrowser.html#webbrowser.register>
that explains the options for webbrowser.register(). It looks like in
Python 3.7, the webbrowser.register() "preferred" argument only takes
keywords now.


 edit the code directly, here is the new code for line 75 in the file
"/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py":


webbrowser.register('chromium-browser', None,
webbrowser.Chrome('chromium-browser'), preferred=True)


(Make sure to leave the spaces from the original line of code in front of
the new code segment as spacing matters in Python).

**Comment by downeyjar** [comment]
i have raspberry pi 4
