### ISSUE TITLE
Error trying to run cloudspeech_demo.py in AIY Voice Kit

### ISSUE THREAD

**Issue by afrdt** [google/aiyprojects-raspbian#677]
Hello, 

My voice kit was working perfectly and I had written custom scripts based on the cloudspeech_demo.py example and everything was working perfectly until two weeks ago that suddenly nothing was running and I kept getting errors without any changes.

I am now trying to run the basic cloudspeech_demo.py script from here: https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/examples/voice/cloudspeech_demo.py and I keep getting this error:

Traceback (most recent call last):
  File "./cloudspeech_demo.py", line 71, in <module>
    main()
  File "./cloudspeech_demo.py", line 41, in main
    parser.add_argument('--language', default=locale_language())
  File "./cloudspeech_demo.py", line 34, in locale_language
    language, _ = locale.getdefaultlocale()
  File "/usr/lib/python3.5/locale.py", line 558, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Any suggestions?

**Comment by afrdt** [comment]
Solved by opening: nano ~/.bash_profile 

Adding:
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

Saving it and then running the script seems to have made the trick.
