### ISSUE TITLE
Error while running tts.py using sudo

### ISSUE THREAD

**Issue by titusece** [google/aiyprojects-raspbian#682]
Hi,

As per this document, executed 'python ~/AIY-projects-python/src/aiy/voice/tts.py "hello world" to convert text to speech, but failing when I run in sudo root privilege.
https://aiyprojects.readthedocs.io/en/latest/aiy.voice.tts.html
Tried python3 too.
Any insights on this ?
Thanks.

```
pi@raspberrypi:~ $ python ~/AIY-projects-python/src/aiy/voice/tts.py "hello world"
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ sudo python ~/AIY-projects-python/src/aiy/voice/tts.py "hello world"
Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/aiy/voice/tts.py", line 72, in <module>
    _main()
  File "/home/pi/AIY-projects-python/src/aiy/voice/tts.py", line 68, in _main
    device=args.device)
  File "/home/pi/AIY-projects-python/src/aiy/voice/tts.py", line 52, in say
    with tempfile.NamedTemporaryFile(suffix='.wav', dir=RUN_DIR) as f:
  File "/usr/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/run/user/0/tmpC3KxCi.wav'
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ sudo python ~/AIY-projects-python/src/aiy/voice/tts.py "hello world"
Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/aiy/voice/tts.py", line 72, in <module>
    _main()
  File "/home/pi/AIY-projects-python/src/aiy/voice/tts.py", line 68, in _main
    device=args.device)
  File "/home/pi/AIY-projects-python/src/aiy/voice/tts.py", line 52, in say
    with tempfile.NamedTemporaryFile(suffix='.wav', dir=RUN_DIR) as f:
  File "/usr/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/run/user/0/tmpQLiULx.wav'
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ python ~/AIY-projects-python/src/aiy/voice/tts.py "hello world"
pi@raspberrypi:~ $ 
```

**Comment by titusece** [comment]
Update:
I've created '/run/user/0/' folder and ran via sudo, it worked.
```
sudo mkdir -p /run/user/0/
sudo python ~/AIY-projects-python/src/aiy/voice/tts.py "hello world"
```
Thanks.
