### ISSUE TITLE
gpiozero/pins.py error:  missing arguments 'ticks' and 'state'

### ISSUE THREAD

**Issue by rudjer** [google/aiyprojects-raspbian#709]
I'm running AIY 2019-11-13 on a V2 Voice Bonnet. The assistant demo works perfectly, but I can't get button input to respond via the gpio pins.  I have a simple button circuit  connected to GND and Pin D on the bonnet, running gpiozero/bonnet.button.py produces these messages:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/AIY-projects-python/src/aiy/pins.py", line 475, in _poll
    callback()
TypeError: _pin_changed() missing 2 required positional arguments: 'ticks' and 'state'

which seems to be traceable back to
 def _pin_changed(self, ticks, state):
        # XXX This is a bit of a hack; _fire_events takes *is_active* rather
        # than *value*. Here we're assuming no-one's overridden the default
        # implementation of *is_active*.
        self._fire_events(ticks, bool(self._state_to_value(state)))

in the code here:  https://github.com/gpiozero/gpiozero/blob/master/gpiozero/input_devices.py
or here on the pi:  /usr/lib/python3/dist-packages/gpiozero/input_devices.py

Any advice would be greatly appreciated.

**Comment by rudjer** [comment]
I've just tried reflashing a new card with the AIY Kits Release 2020-11-20 image.  Unhappily, this produces
the same behavior described above.

**Comment by rudjer** [comment]
I've decided to try the suggestion at #702 and separate the hat from the rpi0 and give up on using the GPIO pins on my V2 voice bonnet.  However, I am somewhat perplexed by the various sources for the  relevant pinout information.  It seems that the most recent is: https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/docs/voice.md but this differs somewhat from what was suggested to @KKeiser by @dmitriykovalev  in July of 2018, in #331 and is yet different from what is given in pinouts.xyz.  If someone could clarify which pins would need to be connected with jumper wires, it would be most appreciated.  I should stipulate that I'm quite naive about such matters, so if the apparent  differences in these pinouts are easily rationalized by the more experienced, I apologize.

**Comment by rudjer** [comment]
FWIW, I've now pulled apart the boards and jumper'd the boards as in the GitHub pinout referenced in my prior comment.  But I now find that the check.audio script returns:  You do not have any sound cards installed.   Of course, it is always possible that I've misaligned some jumper, and will check further.

**Comment by rudjer** [comment]
I've finally opted to adopt the belt and suspenders approach and used the union of the pinout diagrams referenced above.  Fortunately, this yields a functional google assistant and leaves me rpi0 pins 7 and 9 for my button app.  Seems like a ridiculous work around, given that the bonnet has four GPIO pins free, but as explained above I could not make them work for input.
